//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assesment
{
    using System;
    using System.Collections.Generic;
    
    public partial class userer
    {
        public Nullable<int> id { get; set; }
        public string namee { get; set; }
        public string email { get; set; }
        public string mobile_number { get; set; }
        public string passworde { get; set; }
        public Nullable<int> age { get; set; }
        public string city { get; set; }
        public string gender { get; set; }
        public string typee { get; set; }
    }
}
